[package]
name = "locale"
description = "Library for getting the user's localisation settings"
authors = ["Ben S <ogham@bsago.me>", "Jan Hudec <bulb@ucw.cz>"]

documentation = "http://ogham.rustdocs.org/locale/"
homepage = "https://github.com/ogham/rust-locale"
license = "MIT"
readme = "README.md"
version = "0.1.8"

[dependencies]
libc = "0.1"
